%%{init: {"flowchart": {"curve": "stepBefore", "nodeSpacing": 38, "rankSpacing": 62}}}%%
flowchart LR
    A["校园活动系统"]

    A --> B["账号与身份"]
    A --> C["活动服务"]
    A --> D["报名与记录"]
    A --> E["组织者工作台"]
    A --> F["管理审核"]

    B --> B1["用户注册"]
    B --> B2["用户登录"]
    B --> B3["角色区分"]
    B --> B4["个人统计"]

    C --> C1["首页推荐"]
    C --> C2["活动列表"]
    C --> C3["分类筛选"]
    C --> C4["关键词搜索"]
    C --> C5["活动详情"]

    D --> D1["活动报名"]
    D --> D2["取消报名"]
    D --> D3["我的活动"]
    D --> D4["报名状态查看"]

    E --> E1["创建活动"]
    E --> E2["编辑活动"]
    E --> E3["活动信息维护"]
    E --> E4["提交审核"]
    E --> E5["组织活动列表"]

    F --> F1["待审活动查看"]
    F --> F2["审核意见填写"]
    F --> F3["审核通过"]
    F --> F4["审核驳回"]
    F --> F5["审核状态管理"]

    classDef box fill:#ffffff,stroke:#475569,color:#111827,stroke-width:1px;
    class A,B,C,D,E,F,B1,B2,B3,B4,C1,C2,C3,C4,C5,D1,D2,D3,D4,E1,E2,E3,E4,E5,F1,F2,F3,F4,F5 box;
