spring:
  application:
    name: activity-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/campus_activity_v2?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.campus.activity.entity,com.campus.activity.entity.view
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
    call-setters-on-nulls: true

logging:
  level:
    com.campus.activity.mapper: debug
